.DEFAULT_GOAL := prepare
prepare:
	@echo "Nyaaa~"
	@mkdir make
	@cd make
	
config:
	@echo "Making config"
	touch make/FEM_CONFIG
	@echo "Edit the FEM_CONFIG file to change the configuration of FemboyOS, the default is the base OS."
compile:
	@echo "Compiling"
clean:
	rm -rf make/
distclean:
	rm -rf make/
iso:
	echo "WIP :3"